### ISSUE TITLE
Lecture 11 - The Hypergeometric and Negative Binomial Distributions 6/17

### ISSUE THREAD

**Issue by timsoares** [sjbonner/Lectures#2]
On slide 6/17 of lecture 11, the variance for the binomial approximation for the hypergeometric distribution is written incorrectly. It should be _V(X) = np(1-p)_ 
This is the formula used in the following example as well as in the midterm solutions (question 12.e)
![Screen Shot 2024-12-17 at 4 34 16 PM](https://github.com/user-attachments/assets/fca93fb6-1625-4e23-87cc-668402289183)

**Comment by sjbonner** [comment]
Hi @timsoares. Thanks for submitting this. However, I believe that the expressions for the variance provided on the slide appear to be correct. The first expression labelled Variance is the variance of the hypergeometric but written in terms of p instead of M and N. The leading term (N-n)/(N-1) is the correction for sampling without replacement need with the hypergeometric. The second expression is the variance of the binomial, exactly as you gave, which is approximately correct when N is much larger than n so that the correction is close to 1.

I hope that this clarifies the slide.

Cheers,

Simon
